# Generated by Django 4.1.1 on 2022-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation_report",
            name="average_CO2_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="simulation_report",
            name="average_cost_score",
            field=models.IntegerField(default=0),
        ),
    ]
