# Generated by Django 4.1.1 on 2022-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field_Related_Info",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("demand_info", models.CharField(max_length=200)),
                ("wind_info", models.CharField(max_length=200)),
                ("solar_info", models.CharField(max_length=200)),
                ("fossil_fuels_info", models.CharField(max_length=200)),
                ("nuclear_info", models.CharField(max_length=200)),
                (
                    "fossil_fuels_utilisation_percentage_info",
                    models.CharField(max_length=200),
                ),
                (
                    "nuclear_fuels_utilisation_percentage_info",
                    models.CharField(max_length=200),
                ),
                ("surplus_info", models.CharField(max_length=200)),
                ("shortfall_info", models.CharField(max_length=200)),
                ("initial_stored_info", models.CharField(max_length=200)),
                ("final_stored_info", models.CharField(max_length=200)),
                ("storage_discrepancy_info", models.CharField(max_length=200)),
                ("efficiency_score_info", models.CharField(max_length=200)),
                ("total_CO2_tonnes_info", models.CharField(max_length=200)),
                ("total_cost_million_pounds_info", models.CharField(max_length=200)),
                ("average_CO2_tonnes_per_gwh_info", models.CharField(max_length=200)),
                (
                    "average_cost_million_pounds_per_gwh_info",
                    models.CharField(max_length=200),
                ),
            ],
        ),
    ]
