# Generated by Django 4.1.1 on 2023-02-13 12:20

from django.db import migrations, models

import greening_the_spark.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0002_alter_field_related_info_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Three_Dimensional_Models",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model_url",
                    models.ImageField(
                        storage=greening_the_spark.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
