# Generated by Django 4.1.1 on 2023-02-13 12:22

from django.db import migrations, models

import greening_the_spark.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0003_three_dimensional_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Three_Dimensional_Model",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_title", models.CharField(max_length=30)),
                (
                    "model_url",
                    models.ImageField(
                        storage=greening_the_spark.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Three Dimensional Model",
                "verbose_name_plural": "Three Dimensional Models",
            },
        ),
        migrations.DeleteModel(name="Three_Dimensional_Models",),
    ]
