# Generated by Django 4.1.1 on 2023-02-13 12:51

from django.db import migrations, models

import greening_the_spark.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0004_three_dimensional_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="three_dimensional_model",
            name="model_url",
            field=models.FileField(
                storage=greening_the_spark.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
    ]
