# Generated by Django 4.1.1 on 2023-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0006_alter_three_dimensional_model_model_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="three_dimensional_model",
            name="model_title",
            field=models.CharField(
                choices=[
                    ("economy spark red", "economy spark red"),
                    ("economy spark blue", "economy spark blue"),
                    ("economy spark green", "economy spark green"),
                    ("eco spark red", "eco spark red"),
                    ("eco spark blue", "eco spark blue"),
                    ("eco spark green", "eco spark green"),
                    ("efficiency spark red", "efficiency spark red"),
                    ("efficiency spark blue", "efficiency spark blue"),
                    ("efficiency spark green", "efficiency spark green"),
                    ("info model", "info model"),
                    ("efficiency spark green", "efficiency spark green"),
                ],
                max_length=30,
            ),
        ),
    ]
