# Generated by Django 4.1.1 on 2023-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greening_the_spark_api", "0009_alter_three_dimensional_model_model_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation_report",
            name="batteries_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="demand_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="fossil_fuels_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="grid_surplus_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="hydro_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="nuclear_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="solar_power_data_values",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="simulation_report",
            name="wind_power_data_values",
            field=models.CharField(max_length=300),
        ),
    ]
