# Generated by Django 4.1.1 on 2023-06-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "greening_the_spark_api",
            "0010_alter_simulation_report_batteries_power_data_values_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulation_report", name="efficiency_score",
        ),
    ]
