# Generated by Django 4.1.1 on 2023-07-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "greening_the_spark_api",
            "0012_rename_average_co2_tonnes_per_gwh_simulation_report_average_co2_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulation_report",
            old_name="nuclear_fuels_utilisation",
            new_name="nuclear_utilisation",
        ),
    ]
