# Generated by Django 4.1.1 on 2023-09-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greening_the_spark_api', '0013_rename_nuclear_fuels_utilisation_simulation_report_nuclear_utilisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field_related_info',
            old_name='average_CO2_tonnes_per_gwh_info',
            new_name='average_CO2_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='average_cost_million_pounds_per_gwh_info',
            new_name='average_cost_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='efficiency_score_info',
            new_name='fossil_fuels_utilisation_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='fossil_fuels_utilisation_percentage_info',
            new_name='nuclear_utilisation_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='nuclear_fuels_utilisation_percentage_info',
            new_name='storage_change_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='storage_discrepancy_info',
            new_name='total_CO2_info',
        ),
        migrations.RenameField(
            model_name='field_related_info',
            old_name='total_CO2_tonnes_info',
            new_name='total_cost_info',
        ),
        migrations.RemoveField(
            model_name='field_related_info',
            name='total_cost_million_pounds_info',
        ),
    ]
