# Generated by Django 4.1.1 on 2024-01-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greening_the_spark_api', '0014_rename_average_co2_tonnes_per_gwh_info_field_related_info_average_co2_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation_report',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulation_report',
            name='shortfall',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulation_report',
            name='surplus',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulation_report',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
